server:
  port: 8097
  context-path: /
  max-http-header-size: 100000
eureka:
  client:
    service-url:
       defaultZone: http://root:root@localhost:8761/eureka
  instance:
    metadata-map:
      cluster: rest
      management:
        context-path: /actuator
    health-check-url-path: /actuator/health
