spring:
  profiles:
    active: dev
  application:
    name: eureka-service
  security:
    basic:
      enabled: true
    user:
      name: root
      password: root
eureka:
  client:
    register-with-eureka: false
  server:
    enable-self-preservation: false
    fetch-registry: false
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
