server:
  port: 8084
  context-path: /
  max-http-header-size: 100000
eurkea:
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:9701/eureka/
  instance:
    metadata-map:
      cluster: BITCHAIN-ADMIN
      management:
        context-path: /actuator
    health-check-url-path: /actuator/health